### ISSUE TITLE
problem calc_counting_acc.py

### ISSUE THREAD

**Issue by qqphung** [eslambakr/T2I_benchmark#1]
Great work!
I have a problem when running calc_counting_acc.py 
this line  img_id += (level * int(len(gt_objs) / 3))  in cal_acc function,
https://github.com/eslambakr/HRS_benchmark/blob/da709b3ad5629801b62d8c1abd585a028a90f205/codes/eval_metrics/counting/calc_counting_acc.py#L58

Why does img_id start  at level * len(gt_objs) / 3?  Becasue length of gt_objs  in cal_acc function is the length of gt_objs  in the main function / 3? 
So I think this line code should be:
img_id += (level * int(len(gt_objs)))

**Comment by eslambakr** [comment]
Hi @qqphung ,

Thanks for your interest in our work!
Secondly, I am so sorry for the late reply!

No, it is divided by 3 as we want to split the prompts into three hardness levels as mentioned in the paper.
In other words, during the design of our prompts, we are generating easy prompts for the first third of the prompts, then the second third will be medium level and the last is the hardest one.

Therefore, we divide by 3 to report the performance for each hardness level separately.

If you have any further inquires, please let me know.
Have a nice day!
